#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
cnt=1
while [ $cnt -lt 21 ]; do
    echo "$cnt"
    case $cnt in
        4)
            echo "bad luck from China"
            ;;
        5)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((cnt++))
done
