#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hours=0
while [ $hours -lt 13 ]; do
    mins=1
    echo "Hour: $hours"
    while [ $mins -lt 60 ]; do
        echo "$mins"
        ((mins++))
    done
    ((hours++))
done
